
import type { ImagePlaceholder } from './placeholder-images';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  if (!image) throw new Error(`Image with id "${id}" not found.`);
  return image;
};

export type BlogPost = {
  id: string;
  title: string;
  summary: string;
  date: string;
  category: string;
  image: ImagePlaceholder;
};

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'post-1',
    title: 'How to Yap: A Guide to Not Being Awkward',
    summary: 'Feeling weird about starting a convo? Same. Here are some low-key tips to break the ice without trying too hard.',
    date: 'July 28, 2024',
    category: 'Vibes',
    image: findImage('avatar-1'),
  },
  {
    id: 'post-2',
    title: 'Keeping it Chill: Our Safety Promise',
    summary: 'Your safety is the main character. Here\'s the tea on how we keep the weirdos out and the good vibes in.',
    date: 'July 25, 2024',
    category: 'Safety',
    image: findImage('avatar-2'),
  },
  {
    id: 'post-3',
    title: 'Why Anonymous Chat is Actually... Good?',
    summary: 'No profiles, no history, just talking. We think it\'s a pretty sweet deal. Here\'s why it just hits different.',
    date: 'July 22, 2024',
    category: 'Thoughts',
    image: findImage('avatar-3'),
  },
  {
    id: 'post-4',
    title: 'Omegle is Gone, But The Vibes Arent',
    summary: 'RIP Omegle. We\'re here to keep the spirit of random chats alive, but like, way less chaotic.',
    date: 'August 1, 2024',
    category: 'Community',
    image: findImage('blog-4'),
  },
  {
    id: 'post-5',
    title: 'How We\'re Different from Chitchat.gg',
    summary: 'You\'ve seen other chat sites. Here\'s the tea on how yapping is creating a safer, cuter space for Gen Z.',
    date: 'August 2, 2024',
    category: 'Community',
    image: findImage('blog-5'),
  },
  {
    id: 'post-6',
    title: 'Talk to Strangers, No Strings Attached',
    summary: 'The beauty of yapping is the no-login life. Hop on, chat, hop off. It\'s that simple. No digital footprint.',
    date: 'August 3, 2024',
    category: 'Privacy',
    image: findImage('blog-9'),
  },
  {
    id: 'post-7',
    title: 'How to Respectfully Talk to Girls Online',
    summary: 'It\'s not rocket science, it\'s just about being a decent human. Here are some tips to make everyone feel comfy.',
    date: 'August 4, 2024',
    category: 'Vibes',
    image: findImage('blog-12'),
  },
  {
    id: 'post-8',
    title: 'The Unwritten Rules of Gen Z Slang',
    summary: 'From "bet" to "no cap," we\'re decoding the slang so you don\'t sound like a fossil. You\'re welcome.',
    date: 'August 5, 2024',
    category: 'Gen Z',
    image: findImage('blog-10'),
  },
  {
    id: 'post-9',
    title: 'Is It Even a Convo if There Are No Memes?',
    summary: 'A deep dive into the importance of meme-sharing in modern friendships. The answer is no, btw.',
    date: 'August 6, 2024',
    category: 'Gen Z',
    image: findImage('blog-13'),
  },
  {
    id: 'post-10',
    title: 'The Legacy of Random Chat: From AOL to Yapping',
    summary: 'A little history lesson on how we got here. The internet has always been about connecting with randoms.',
    date: 'August 7, 2024',
    category: 'Community',
    image: findImage('blog-8'),
  },
  {
    id: 'post-11',
    title: 'Finding Your People Without Leaving Your Room',
    summary: 'Introverts, unite! Separately. In your own homes. Here\'s how to make friends online without the social battery drain.',
    date: 'August 8, 2024',
    category: 'Vibes',
    image: findImage('blog-11'),
  },
  {
    id: 'post-12',
    title: 'Why You Don\'t Need to Login to Find a Friend',
    summary: 'We believe in privacy and low-pressure chats. That starts with not needing your life story to start yapping.',
    date: 'August 9, 2024',
    category: 'Privacy',
    image: findImage('blog-9'),
  },
  {
    id: 'post-13',
    title: 'Let\'s Talk Consent: Making Online Chats Safe',
    summary: 'Consent isn\'t just for IRL. It\'s about making sure the person you\'re chatting with is cool with the convo. Always.',
    date: 'August 10, 2024',
    category: 'Safety',
    image: findImage('blog-6'),
  },
  {
    id: 'post-14',
    title: 'The Art of the "Next" Button',
    summary: 'Not feeling the vibe? It\'s okay to dip. The "Next" button is your best friend. No guilt, no drama.',
    date: 'August 11, 2024',
    category: 'Tips',
    image: findImage('blog-5'),
  },
  {
    id: 'post-15',
    title: 'Beating the Awkward: Icebreakers that Actually Work',
    summary: '"wyd" is dead. Here are some actually interesting ways to start a conversation with a stranger.',
    date: 'August 12, 2024',
    category: 'Tips',
    image: findImage('avatar-1'),
  },
  {
    id: 'post-16',
    title: 'The Gen Z Guide to Digital Etiquette',
    summary: 'From ghosting to double-texting, the rules are weird. Let\'s break down how to be a good digital citizen.',
    date: 'August 13, 2024',
    category: 'Gen Z',
    image: findImage('blog-10'),
  },
  {
    id: 'post-17',
    title: 'Chat Roulette without the... well, you know.',
    summary: 'The thrill of the random, none of the trauma. How we learned from the past to build a better chat site.',
    date: 'August 14, 2024',
    category: 'Community',
    image: findImage('blog-8'),
  },
  {
    id: 'post-18',
    title: 'How to Yap with Anyone, About Anything',
    summary: 'You don\'t need to have a ton in common to have a good conversation. It\'s all about curiosity.',
    date: 'August 15, 2024',
    category: 'Tips',
    image: findImage('blog-11'),
  },
  {
    id: 'post-19',
    title: 'No Sign-Up, No Problem: The Freedom of Anonymous Chat',
    summary: 'Explore the web without leaving a trace. Why we\'re committed to the no-login life.',
    date: 'August 16, 2024',
    category: 'Privacy',
    image: findImage('blog-9'),
  },
  {
    id: 'post-20',
    title: 'Friendships in the Digital Age: It\'s Complicated',
    summary: 'Making friends online is normal now. Let\'s talk about how to navigate these unique connections.',
    date: 'August 17, 2024',
    category: 'Thoughts',
    image: findImage('blog-6'),
  },
  {
    id: 'post-21',
    title: 'Beyond the DM: Meaningful Convos with Strangers',
    summary: 'Tired of surface-level chats? Us too. Here\'s how to go deeper and have conversations that actually stick.',
    date: 'August 18, 2024',
    category: 'Tips',
    image: findImage('blog-12'),
  },
  {
    id: 'post-22',
    title: 'What\'s Your Digital Body Language?',
    summary: 'Typing speed, emoji use, punctuation... it all says something. What are your texts saying about you?',
    date: 'August 19, 2024',
    category: 'Gen Z',
    image: findImage('blog-13'),
  },
  {
    id: 'post-23',
    title: 'The End of an Era: What We Learned from Omegle\'s Shutdown',
    summary: 'Omegle\'s closure left a void. We\'re exploring what made it special and what pitfalls to avoid.',
    date: 'August 20, 2024',
    category: 'Community',
    image: findImage('blog-4'),
  },
  {
    id: 'post-24',
    title: 'Why Yapping is Better than Your Group Chat',
    summary: 'Sometimes you need a fresh perspective. Talking to a stranger can be more freeing than talking to your friends.',
    date: 'August 21, 2024',
    category: 'Thoughts',
    image: findImage('blog-5'),
  },
  {
    id: 'post-25',
    title: 'The Simple Joy of a No-Stakes Conversation',
    summary: 'No expectations. No history. Just a moment of connection. There\'s a special kind of magic in that.',
    date: 'August 22, 2024',
    category: 'Vibes',
    image: findImage('avatar-2'),
  },
  {
    id: 'post-26',
    title: 'How to Talk to People IRL (lessons from online chat)',
    summary: 'Believe it or not, the skills you learn yapping online can actually help you be less awkward in real life.',
    date: 'August 23, 2024',
    category: 'Tips',
    image: findImage('blog-11'),
  },
  {
    id: 'post-27',
    title: 'Is Anonymity the Key to Authenticity?',
    summary: 'When no one knows who you are, are you more likely to be yourself? We think so.',
    date: 'August 24, 2024',
    category: 'Thoughts',
    image: findImage('blog-9'),
  },
  {
    id: 'post-28',
    title: 'Creating a Positive Corner of the Internet',
    summary: 'The internet can be a dumpster fire. We\'re trying to be the cozy little campfire. Here\'s how you can help.',
    date: 'August 25, 2024',
    category: 'Safety',
    image: findImage('blog-6'),
  },
  {
    id: 'post-29',
    title: 'Main Character Energy: How to Own Your Online Presence',
    summary: 'Even when you\'re anonymous, you have a vibe. Here\'s how to bring that main character energy to every chat.',
    date: 'August 26, 2024',
    category: 'Gen Z',
    image: findImage('blog-10'),
  },
  {
    id: 'post-30',
    title: 'The Future of Yapping: What\'s Next?',
    summary: 'We\'re always dreaming up new ways to connect. Here\'s a sneak peek at what we\'re working on.',
    date: 'August 27, 2024',
    category: 'Community',
    image: findImage('blog-7'),
  },
  {
    id: 'post-31',
    title: 'Good Banter: A Lost Art?',
    summary: 'In an age of swiping and scrolling, is the art of just talking lost? We don\'t think so.',
    date: 'August 28, 2024',
    category: 'Thoughts',
    image: findImage('blog-12'),
  },
  {
    id: 'post-32',
    title: 'From Lurker to Yapper: Your Journey Starts Here',
    summary: 'Been silently scrolling? It\'s time to jump in. The water\'s fine, and the people are (mostly) nice.',
    date: 'August 29, 2024',
    category: 'Tips',
    image: findImage('avatar-3'),
  },
  {
    id: 'post-33',
    title: 'Digital Hangouts: The New Third Place',
    summary: 'Your home is one place, work/school is another. For Gen Z, digital spaces are the "third place" to hang.',
    date: 'August 30, 2024',
    category: 'Gen Z',
    image: findImage('blog-11'),
  }
];
